gh-1419: Added deprecation workflow for CPython.
python/devguide pull request #1469
Opened 2024-11-08 12:29 UTC by Lincoln-developer

This pull request introduces a new section in the Developer Guide to document the practical steps for deprecating features in CPython. It complements the policy guidelines outlined in [PEP 387](https://peps.python.org/pep-0387/) by providing a detailed, actionable workflow for contributors

2024-11-08 13:00 UTC, AA-Turner requested changes
I think we can make a few improvements here specific to CPython.

A

P.S. Out of idle curiosity, did you use an LLM/GPT to help write this document? There's a couple of hallmarks I recognise, but it could just be a general style!

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +* **Assess Usage**: Use tools like GitHub search, ``grep``, or ``PyPI statistics`` to determine the extent and context of usage.
Perhaps you could add links here?

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +* Encourage community feedback and suggestions.
Perhaps discuss if/when Discourse should be used instead
```suggestion
Open an issue
-------------

Start by creating a GitHub issue to propose the deprecation:

* Clearly describe the feature and why deprecation is needed.
* Encourage community feedback and suggestions.
```

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +Once approved:
```suggestion
Deprecation implementation
--------------------------

Once approved:
```

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +---------------------
```suggestion
Track deprecations
------------------

```

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +After the deprecation period (typically 2+ releases):
```suggestion
Plan removal
------------

After the deprecation period (not less than two releases):
```

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +For gradual deprecations:
```suggestion
``PendingDeprecationWarning`` workflow
--------------------------------------

For gradual deprecations:
```

2024-11-08 13:00 UTC, AA-Turner commented on developer-workflow/cpython-deprecation-workflow.rst
> +* Use ``.. deprecated::`` and ``.. removed::`` Sphinx roles for documentation.
```suggestion
References and templates
------------------------

* Use the ``.. deprecated-removed::`` roles for documentation.
```

2024-11-08 13:07 UTC, Lincoln-developer commented on developer-workflow/cpython-deprecation-workflow.rst
> +     )
Thanks let me work on this change

2024-11-08 13:08 UTC, Lincoln-developer commented on developer-workflow/cpython-deprecation-workflow.rst
> +* **Assess Usage**: Use tools like GitHub search, ``grep``, or ``PyPI statistics`` to determine the extent and context of usage.
okay sure, let me add them

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +* **Raise a Warning**: Use ``warnings._deprecated`` with :exc:`DeprecationWarning` for typical cases.
Why is this preferred over the documented and more common `warnings.warn` (over 3x in the stdlib)?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +==============================================
```suggestion
Workflow for Deprecating Features in CPython
============================================
```

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +Deprecation in CPython is a multi-step process that involves notifying users about deprecated functionality, planning its eventual removal, and providing adequate guidance for migration.
Please wrap lines to 79 characters.

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +* **Assess Usage**: Use tools like GitHub search, `grep`_, or `PyPI statistics`_ to determine the extent and context of usage.
Maybe add a link to the GitHub search and list Victor's script: https://hugovk.dev/blog/2022/how-to-search-5000-python-projects/ ?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +Start by creating a GitHub issue to propose the deprecation:
I think we should recommend a thread on Discourse first?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +  * Use :exc:`PendingDeprecationWarning` initially, which transitions to :exc:`DeprecationWarning` after a suitable period.
We rarely use `PendingDeprecationWarning`, I think we can drop it?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +  Example:
This example would be more beneficial if an example feature existed, a function would add a lot IMO

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +  * Include details in the "Porting" section of the "What's New" documentation.
```suggestion
  * Include details in the "New Deprecations" section of the "What's New" documentation.
```

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +* **Timeline Review**: Use GitHub milestones or specific deprecation tracking issues to manage timelines.
> GitHub milestones

These are not used in CPython?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +``PendingDeprecationWarning`` workflow
This stage seems odd, how often is this done?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +* Add ``See Also`` links to :pep:`387` and DevGuide for policy and process details.
I don't understand, do you suggest a `.. see-also::` under every deprecated feature?

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/cpython-deprecation-workflow.rst
> +------------------------
We can also link to PEP 4

2025-09-08 20:59 UTC, StanFromIreland commented on developer-workflow/index.rst
> +   cpython-deprecation-workflow
This should definitely be below `development cycle`

2026-06-21 04:30 UTC, sirosen commented
I see that at least three people have put in effort here, but it's stalled. I can carry it forward, if that seems appropriate.

@StanFromIreland , as the most recent reviewer, what would you think of me picking this up and continuing the work in a new PR?
(I'd preserve these commits, but open a fresh PR with my additions.)

2026-06-21 09:59 UTC, StanFromIreland commented
@sirosen yes, it would be great for someone to pick this up, this has been stale for a while. I would suggest that whoever does pick it up do at least one deprecation in CPython beforehand. I think part of the issue here was that current practices aren't written down, which made it easy to end up inventing new ones. If you have any questions while working on this, feel free to ask/ping me.

Other things worth covering here would be soft deprecations. I also wouldn't focus too much on the "When to deprecate?" section, that's a difficult topic and all cases can't be covered by the docs, some general guidelines would suffice. In the future we could also expand the section to cover removing the deprecated items, as this gets difficult e.g. when things are in the stable ABI.

2026-06-21 10:05 UTC, hugovk commented
And might be worth starting this guide from scratch, rather than continuing from this PR.

2026-06-25 20:15 UTC, sirosen commented
> I would suggest that whoever does pick it up do at least one deprecation in CPython beforehand. I think part of the issue here was that current practices aren't written down, which made it easy to end up inventing new ones. If you have any questions while working on this, feel free to ask/ping me.

Unfortunately, that would rule me out as a candidate to carry this work forward. Maybe that's okay, but I am also happy to write down current practice with a bit of guidance. I'll circle back on the idea -- there might be other places where I can be more helpful.

---

Given that review time was sunk into this, rather than it being closed, I was under the impression that it was close (or close enough) to be worth carrying on and preserving commits/credit.
However, I now see the CLA Signing check is also blocked, so we can't take this work anyway. I recommend closing this.

2026-06-25 20:17 UTC, closed without merging

2026-06-25 20:18 UTC, StanFromIreland commented
> CLA Signing check

Based on the bot's comment above, it's alright. But this has been stale for a long time, so I think it's time to close anyway.

2026-06-25 20:21 UTC, sirosen commented
Oh, I hadn't noticed the comment, only the GHA check status. Odd that they got out of alignment, but okay anyway. :smile:

2026-06-25 20:27 UTC, StanFromIreland commented
It sometimes get stuck like that, if I re-opened it would re-run and go green.