Solved issue #522 #623
python/devguide pull request #638
Opened 2020-10-25 05:17 UTC by aliya-rahmani

Simplified language in translation page

2021-01-04 19:16 UTC, Mariatta requested changes
Thanks for the PR. Can you please rebase your branch?

I think most of the links should stay. The only change here is the addition of the `_mail_pl` link. The rest of the change should be reverted.

2021-01-04 19:16 UTC, Mariatta commented on documenting.rst
> -.. _github_pl: https://github.com/python/python-docs-pl
This link looks correct.

2021-01-04 19:16 UTC, Mariatta commented on documenting.rst
> -.. _doc_pl: https://docs.python.org/pl/
This link is correct.

2021-01-04 19:16 UTC, Mariatta commented on documenting.rst
> +Ask for help on the doc-sig mailing list
This section has been updated in #649, so this is good now.

2022-01-07 17:22 UTC, hugovk commented
> Thanks for the PR. Can you please rebase your branch?
> 
> I think most of the links should stay. The only change here is the addition of the `_mail_pl` link. The rest of the change should be reverted.

Please see https://github.com/python/devguide/pull/788 which only adds the `_mail_pl` link.

2022-01-28 12:51 UTC, hugovk commented
Closing in favour of https://github.com/python/devguide/pull/788.

2022-01-28 12:51 UTC, closed without merging