Update Ubuntu Bionic to Focal in setup.rst
python/devguide pull request #654
Opened 2021-01-20 18:00 UTC by illia-v

Ubuntu Focal Fossa is the latest LTS release. Its default Python version is 3.8.

Also, I added a numeric version of the Ubuntu release because it is likely more familiar to users.

2022-01-07 17:08 UTC, hugovk approved these changes

2022-01-07 17:08 UTC, hugovk commented
@illia-v Looks good, please could you resolve the conflicts?

2022-06-04 18:48 UTC, ezio-melotti requested changes

2022-06-04 18:48 UTC, ezio-melotti commented on setup.rst
> +Take Ubuntu 20.04 LTS (Focal Fossa) for example::
```suggestion
Take Ubuntu 22.04 LTS (Jammy Jellyfish) for example::
```

2022-06-04 18:48 UTC, ezio-melotti commented on setup.rst
> +   deb-src http://archive.ubuntu.com/ubuntu/ focal main
```suggestion
   deb-src http://archive.ubuntu.com/ubuntu/ jammy main
```

2022-06-04 18:48 UTC, ezio-melotti commented on setup.rst
> +   $ sudo apt-get build-dep python3.8
```suggestion
   $ sudo apt-get build-dep python3.10
```

2022-06-04 18:53 UTC, ezio-melotti approved these changes

2022-06-04 18:53 UTC, merged