Clarify stale label
python/devguide pull request #677
Opened 2021-04-27 08:36 UTC by skirpichev

It seems, most recent "stale" issues got that label just because were unreviewed.  Trying to document this...

2021-04-28 17:52 UTC, Mariatta commented
The stale label is nowadays added by `stale` GitHub Actions. It's not just the "unreviewed", but anything that hasn't had any activity after 30 days.  https://github.com/actions/stale

2021-04-29 02:42 UTC, skirpichev commented
Are you suggesting to simplify the label description even more?

Something like: Used for PRs that hasn't had any activity in a long period of time. This label helps core developers quickly identify PRs that are candidates for closure, for review or require a ping to the author.

2022-01-07 17:05 UTC, hugovk requested changes
> Are you suggesting to simplify the label description even more?
> 
> Something like: Used for PRs that hasn't had any activity in a long period of time. This label helps core developers quickly identify PRs that are candidates for closure, for review or require a ping to the author.

That sounds good to me, it includes the "candidate for review" possibility too.

Except also include this grammar fix and let's explicitly mention the 30 days:

```diff
-Used for PRs that hasn't had any activity in a long period of time.
+Used for PRs that haven't had any activity in 30 days.
```

2022-01-12 11:03 UTC, hugovk approved these changes

2022-02-10 04:21 UTC, closed without merging