Fix some incorrect links
python/devguide pull request #831
Opened 2022-04-14 07:08 UTC by slateny

(some found via `make linkcheck`)

2022-04-14 09:13 UTC, hugovk approved these changes
Thank you!

2022-04-14 14:43 UTC, JelleZijlstra commented
There is a merge conflict

2022-04-15 05:44 UTC, slateny commented
Merge conflict was due to the whitespace PR being merged which touched the same section. Fixed it, and also changed some things as per the comments in the GH issue

2022-04-16 23:11 UTC, ezio-melotti requested changes

2022-04-16 23:11 UTC, ezio-melotti commented on buildworker.rst
> +      <https://web.archive.org/web/20201113084744/http://trac.buildbot.net/wiki/RunningBuildbotOnWindows>`_.
These instructions seem obsolete, this link seems up to date:
```suggestion
      <https://docs.buildbot.net/current/manual/installation/requirements.html#windows-support>`_.
```

2022-04-16 23:15 UTC, ezio-melotti approved these changes

2022-04-16 23:17 UTC, merged